### ISSUE TITLE
Where can I find the Source code?

### ISSUE THREAD

**Issue by kallebysantos** [dotnet-smartcomponents/smartcomponents#13]
I would like to know where can I find the `SmartComponents` source code, is that open source? or pretend to be?

It will be useful for studying as well to extend components functionality.

**Comment by SteveSandersonMS** [comment]
We haven't yet got clearance to open the code, but hopefully that's just a matter of time. The fact that you're saying you want that helps to justify making that happen, so thanks for letting us know.

**Comment by yylai** [comment]
Likewise, +1 to the source code. Really cool stuff! Interested to see how you all map ("databind") the OpenAI responses to the structured components, and understand if there are any optimizations/thoughts to the cost aspect (e.g. there is now a real variable cost for user actions like smart combo box)

**Comment by ScottyBlazor** [comment]
wow cool controls thanks, waiting to see the source code. we are just about to begin our journey in to AI. so would be really helpful

**Comment by Ashijo** [comment]
Not that hard to retro engineered anyway, once the custom tag un-minified the rest isn't that hard to figure, I don't see the point of closing a source that is mainly hidden by minification. 
Hope you will have clearance soon, I cannot use closed source for UI component :(

**Comment by codepend** [comment]
Yes, please make this an official repo/product.

**Comment by quicksln** [comment]
I would like to join and vote +1 - please make this an official repo/product :)

**Comment by tsnyder-gs1us** [comment]
Cool idea, love to see this move forward to become an open source library for developers.

**Comment by ADefWebserver** [comment]
> and amaze our clients.

This is what all of us are thinking... :)

**Comment by Herostwist** [comment]
@SteveSandersonMS out of curiosity, who do you need to get clearance to open the code from and what are the reasons for the current closed status of the project? I'm very keen to experiment with some of this but wary of the closed source.

**Comment by Mimisss** [comment]
> @SteveSandersonMS out of curiosity, who do you need to get clearance to open the code from and what are the reasons for the current closed status of the project? I'm very keen to experiment with some of this but wary of the closed source.

I think one of the reasons is that many of the classes/methods are `internal` to the `Azure.AI.OpenAI` namespace.

**Comment by SteveSandersonMS** [comment]
It took longer than expected, but as requested, we've now made this entirely open-source.

The new repo location is https://github.com/dotnet/smartcomponents, where you'll find the same docs that were here, plus the actual source code.

I'll be marking this repo as archived now, so if you have any further questions or if any of your issues are still active questions, please consider re-posting to the new repo.

Also note that as part of this change, we're putting Smart Components under our "samples" category rather than pre-shipped packages. In part, this is because one of the main things we've learned is that people really want to customize almost everything about them, so working from sources sets you off in the right direction.
