### ISSUE TITLE
Error downloading onnxruntime

### ISSUE THREAD

**Issue by egarim** [dotnet-smartcomponents/smartcomponents#16]
When I add the following package to my project

<PackageReference Include="SmartComponents.LocalEmbeddings" Version="0.1.0-preview10145" />

I got the following error when I build from visual studio

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3027	Could not copy "C:\Users\xarig\.nuget\packages\microsoft.ml.onnxruntime\1.17.0\runtimes\ios\native\onnxruntime.xcframework\ios-arm64_x86_64-simulator\onnxruntime.framework\Headers\onnxruntime_session_options_config_keys.h" to "bin\Debug\net6.0\runtimes\ios\native\onnxruntime.xcframework\ios-arm64_x86_64-simulator\onnxruntime.framework\Headers\onnxruntime_session_options_config_keys.h". Exceeded retry count of 10. Failed. 	XafSmartComponents.Blazor.Server	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	4911	

the error does not happend if you build the project from the console using "dotnet build" or "dotnet run", I'm using windows 10 as OS

**Comment by SteveSandersonMS** [comment]
That's very odd. I don't know why the ONNX package would be trying to copy iOS-related assets to your build output.

Are you building an ASP.NET Core application, or is this a MAUI project?

If you can give repro steps (as in, exactly what project to create, using which SDK version, and what steps to take to get this error) I would definitely investigate.

**Comment by egarim** [comment]
is a Blazor application

**Comment by SteveSandersonMS** [comment]
Thanks for answering, but unfortunately we would need more detailed repro steps in order to investigate. The components work as expected in many other Blazor apps so we would need to figure out what's different about your app or about your dev machine setup.

Since you're saying the problem is specific to Visual Studio in your case (and does not happen when building from CLI) it might be there is a problem with your Visual Studio installation. You might need to uninstall it, and reinstall the latest version.

Sorry I can't give you more precise guidance without more details that could point at the cause!

**Comment by SteveSandersonMS** [comment]
I'll close due to lack of info - I guess you probably resolved it yourself already.

**Comment by SteveSandersonMS** [comment]
@thoemmi That makes it sound like a problem specifically in the `Microsoft.ML.OnnxRuntime` package. Would you consider reporting the issue to the maintainers of that package? I think the repo is at https://github.com/microsoft/onnxruntime/

**Comment by thoemmi** [comment]
FYI: enabling long paths ([Registry setting to enable long paths](https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#registry-setting-to-enable-long-paths)) did the trick. I can now compile successfully
