### ISSUE TITLE
Wrong data filled in for repsonse of llama2:latest on "Smart Paste"

### ISSUE THREAD

**Issue by cheindel** [dotnet-smartcomponents/smartcomponents#22]
I used your example from the documentation and just changed it to localized field names.

Is this behaviour a problem with the local model or with the smartpaste component?

Request: https://localhost:43829/_smartcomponents/smartpaste
{"formFields":[{"identifier":"name","description":"Name:","type":"string"},{"identifier":"strasse","description":"Straße:","type":"string"},{"identifier":"ort","description":"Ort:","type":"string"},{"identifier":"postleitzahl","description":"Postleitzahl:","type":"string"}],"clipboardContents":"Julie-Salinger-Weg+1,+01099+Dresden"}

Response:
FIELD name^^^The Name: of type stringvalue The Name: Julie Salinger
FIELD strasse^^^The Straße: of type stringvalue The Straße: Julie-Salinger-Weg
FIELD ort^^^The Ort: of type stringvalue The Ort: Dresden
FIELD postleitzahl^^^The Postleitzahl: of type stringvalue The Postleitzahl: 01099

Output:
![grafik](https://github.com/dotnet-smartcomponents/smartcomponents/assets/454595/8680b754-5be3-4908-8a16-058fb7bd4aef)

**Comment by SteveSandersonMS** [comment]
Yes, this is the sort of thing that happens with less capable models. Please see the ["model quality" section in docs](https://github.com/dotnet-smartcomponents/smartcomponents/blob/main/docs/configure-openai-backend.md#using-ollama-or-another-self-hosted-endpoint).

I'll close this since it's inevitable that some models will behave better than others, and the docs already try to set expectations about that. However if you find local models you can recommend, or custom prompts (see docs for how) that make it better, please let us know so we can either document it or update the default prompts. Hope that's OK!
