### ISSUE TITLE
Issue assigning ApiKey when project is a Razor Component Library

### ISSUE THREAD

**Issue by leigh-pointer** [dotnet-smartcomponents/smartcomponents#50]
I have a Razor Component Library where I would like to try SmartPaste.  How do I assign the SmartComponents ApiKey ?

Much Thanks

**Comment by SteveSandersonMS** [comment]
You would need it to be configured in the hosting application as usual. It wouldn't normally make sense for a component library to include its own API keys since then anyone who uses the library would be billing their usage to you.

If this doesn't sound right to you, please let me know and we can reopen/discuss further.
